### ISSUE TITLE
Ideate on the application idea we can build

### ISSUE THREAD

**Issue by Riyu44** [Sopra-Banking-Software-Interns/Application-2.0#1]

**Comment by Suvarchala-30** [comment]
@Riyu44 Let's be professional and not include personal comments in the workspace. Kindly use this space for discussing about the project.
Thank You

P.S I'll keep mocking you. (We are in a war as mentioned by you earlier)

**Comment by Tushar-2510** [comment]
it seems suvarchala is offended for Priyansh calling her doms today

**Comment by Tushar-2510** [comment]
https://account.cloudmersive.com/ https://prismic.io/blog/13-best-api-project-ideas
https://rapidapi.com/collection/list-of-free-apis
https://ipapi.co/
https://wit.ai/docs/http/20230215/
https://spoonacular.com/food-api/docs
https://developer.nytimes.com/apis
https://www.themealdb.com/api.php
https://www.thecocktaildb.com/api.php
https://developer.oxforddictionaries.com/documentation
https://responsivevoice.org/text-to-speech-sdk/text-to-speech-play-button/

**Comment by Riyu44** [comment]
guys let's build EVERYTHING...
Here's  how:
Choose at least 4 APIs you want to work with. Write a shell script executing them from start to end. Send a PR and I will merge all of it into one big open API application. Continue the thread with the names of APIs you guys are working with @Tushar-2510 @CodePrakhar @Riyu44 @Suvarchala-30 @navvay

**Comment by Riyu44** [comment]
Here's my list (please avoid working with these):
https://developer.oxforddictionaries.com/documentation
https://restcountries.com/#api-endpoints-using-this-project
https://developer.nytimes.com/apis
https://icanhazdadjoke.com/api

**Comment by Riyu44** [comment]
Please do not send a PR directly instead create a folder with name as 'your_name' and add the changes into it.

**Comment by Tushar-2510** [comment]
My list :-
https://spoonacular.com/food-api/docs#Search-Recipes-by-Ingredients
https://www.boredapi.com
https://www.thecocktaildb.com/api.php
https://imgflip.com/api

**Comment by Riyu44** [comment]
Guys please update the list of APIs you are going to work on.
@CodePrakhar @Suvarchala-30 @navvay

**Comment by navvay** [comment]
I have currently used the following APIs:
1. https://api.datamuse.com/words?sp=$word&md=d
2. https://deckofcardsapi.com/api

**Comment by XpectoPatronum** [comment]
I used https://api.nasa.gov/
and https://api-ninjas.com/api/bucketlist
